import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

// Locally the built main.js is written straight into the installed plugin inside
// the Obsidian vault. If the vault ever moves, update this one path.
const VAULT_PLUGIN = "D:/Obsidian/mrrepac/.obsidian/plugins/russian-rhymes";
// On CI that path is not absolute, so the release workflow would never find the
// bundle: there the artifact belongs in the repository root next to manifest.json.
const outfile = process.env.CI ? "main.js" : `${VAULT_PLUGIN}/main.js`;

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", ...builtinModules],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile
};

if (prod) {
  await esbuild.build(buildOptions);
} else {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
}
