/*
 * Сборка плагина: src/main.ts -> main.js рядом с manifest.json.
 *
 * Вывод намеренно НЕ минифицируется. Во-первых, каталог Obsidian требует читаемую
 * сборку, во-вторых, тестовый стенд вынимает из бандла отдельные классы, разыскивая
 * метки секций («// src/dict.ts») и заголовки вроде «var RhymesView = class extends».
 * Минификация сломала бы и то и другое.
 */
import esbuild from "esbuild";
import process from "node:process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const watch = process.argv.includes("--watch");

const options = {
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "main.js",
  format: "cjs",
  target: "es2018",
  platform: "browser",
  // obsidian даёт хост, встраивать его нельзя; electron и редакторные пакеты тоже внешние
  external: ["obsidian", "electron", "@codemirror/*", "@lezer/*"],
  sourcemap: false,
  minify: false,
  treeShaking: true,
  logLevel: "info",
  banner: { js: banner },
};

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
} else {
  await esbuild.build(options);
}
